# Generated by Django 4.1.2 on 2022-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=60)),
                ('summary', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
