# Generated by Django 4.1.2 on 2022-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_by_day', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
